### ISSUE TITLE
shape mismatch when running default example

### ISSUE THREAD

**Issue by aiXander** [AILab-CVC/VideoCrafter#38]
I'm getting
```
einops.EinopsError:  Error while processing rearrange-reduction pattern "(b h) n d -> b n (h d)".
 Input tensor shape: torch.Size([16, 2560, 320]). Additional info: {'h': 5}.
 Shape mismatch, can't divide axis of length 16 in chunks of 5
 ```
 
 when running the default `sh scripts/run_image2video.sh`

**Comment by Number18-tong** [comment]
I got the same error, have you solved this problem?

**Comment by Mozer** [comment]
add parameter --frames 15 in run_image2video.sh

**Comment by Number18-tong** [comment]
> add parameter --frames 15 in run_image2video.sh

Thanks a lot

**Comment by Number18-tong** [comment]
> add parameter --frames 15 in run_image2video.sh

I've tried, but it doesn't work for me.
 I found that the attention.py has a bug in line 123 as bellows, and after I change the "out" into "out_ip", the error is fixed.
![企业微信截图_1699011443451](https://github.com/AILab-CVC/VideoCrafter/assets/52230160/f15572e0-9e28-4374-be97-eaef80bdcf52)

**Comment by Mozer** [comment]
Thanks! Now it's working.

**Comment by scutpaul** [comment]
Thanks to @Number18-tong. This issue arises in the forward function when xformers are not available, and we'll fix it in a recent commit!
