### ISSUE TITLE
AttributeError: 'VisionTransformer' object has no attribute 'input_patchnorm'

### ISSUE THREAD

**Issue by Laidawang** [AILab-CVC/VideoCrafter#39]
when i try to run  sh scripts/run_image2video.sh i got `AttributeError: 'VisionTransformer' object has no attribute 'input_patchnorm'` All models have been downloaded and placed in the designated location.

**Comment by LetifT** [comment]
I just ran into the same error

**Comment by alittleanimal** [comment]
same problem

**Comment by quartets** [comment]
Same problem

**Comment by jiangyurong609** [comment]
same here

**Comment by 447806664** [comment]
same problem

**Comment by kanik155** [comment]
pip install open-clip-torch==2.12.0

**Comment by ZombaSY** [comment]
> It is an open_clip version issue. pip install open-clip-torch==2.12.0

Currently solved with the versioning:
- torch==2.0.0
- torchvision==0.15.1
- transformers==4.25.1
- open-clip-torch==2.12.0

**Comment by scutpaul** [comment]
Thanks for @kanik155 @ZombaSY, we'll fix this in a recent commit!
