### ISSUE TITLE
AttributeError: 'Row' object has no attribute 'style'

### ISSUE THREAD

**Issue by jutochoppa** [AILab-CVC/VideoCrafter#77]
$ python gradio_app.py 

AE working on z of shape (1, 4, 64, 64) = 16384 dimensions.
 model checkpoint loaded.
AE working on z of shape (1, 4, 64, 64) = 16384 dimensions.
 model checkpoint loaded.
Traceback (most recent call last):
  File "gradio_app.py", line 90, in <module>
    videocrafter_iface = videocrafter_demo(result_dir)
  File "gradio_app.py", line 31, in videocrafter_demo
    with gr.Row().style(equal_height=False):
AttributeError: 'Row' object has no attribute 'style'

**Comment by ordigital** [comment]
$ python gradio_app.py

AE working on z of shape (1, 4, 64, 64) = 16384 dimensions.
>>> model checkpoint loaded.
Traceback (most recent call last):
  File "gradio_app.py", line 55, in <module>
    videocrafter_iface = videocrafter_demo(result_dir)
  File "gradio_app.py", line 26, in videocrafter_demo
    with gr.Row().style(equal_height=False):
AttributeError: 'Row' object has no attribute 'style'
(videocrafter)

**Comment by gjnave** [comment]
> In `requirements.txt` change `gradio` to `gradio==3.41.2`. Then again ` pip install -r requirements.txt` and `python gradio_app.py` should work.

just use pip install gradio==3.41.2 .. no need to re-run requirements

**Comment by jutochoppa** [comment]
Thanks
